volumes:
  pg_data:
  static:
  media:

services:
  postgres:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 3s
      timeout: 3s
      retries: 30

  backend:
    # image: stroge27/kittygram_backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    # image: stroge27/kittygram_frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: sh -c "cp -r /app/build/. /static/"
    restart: 'no'
    volumes:
      - static:/static
    depends_on:
      - backend

  gateway:
    # image: stroge27/kittygram_gateway:latest
    build: ./nginx/
    env_file:
      - .env
    restart: always
    ports:
      - "80:80"
    depends_on:
      frontend:
        condition: service_completed_successfully
      backend:
        condition: service_started
    volumes:
      - static:/staticfiles
      - media:/app/media
