server {
    listen 80;
    client_max_body_size 10M;

    location /media/ {
        alias /var/html/media/;
    }

    location /static/admin/ {
        alias /var/html/static/admin/;
    }

    location /static/rest_framework/ {
        alias /var/html/static/rest_framework/;
    }

    location /static/ {
        proxy_pass http://frontend:8000;
    }

    location ~ ^/(api|admin)/ {
        proxy_pass http://backend:8000;
    }

    location / {
        proxy_pass http://frontend:8000;
    }
}
