#cloud-config
users:
  - name: user
    groups: sudo
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ${SSH_KEY}

write_files:
  - path: /root/vm-install.sh
    permissions: "0740"
    content: |
      #!/bin/bash
      set -e
      apt-get update
      apt-get install -y docker.io docker-compose
      systemctl enable --now docker
      usermod -aG docker user

runcmd:
  - bash /root/vm-install.sh
